import type { Metadata } from 'next'
import './globals.css'
import Navbar from '@/components/Navbar'
import ReactQueryProvider from '@/components/ReactQueryProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ReactQueryProvider>
          <Navbar />
          <main className="pb-[80px]">{children}</main>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
